DROP TABLE IF EXISTS apps CASCADE;
DROP TABLE IF EXISTS hits CASCADE;

CREATE TABLE apps
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(64)                             NOT NULL,
    uri  VARCHAR(64)                             NOT NULL,
    CONSTRAINT pk_app_id PRIMARY KEY (id)
);

CREATE TABLE hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_id    VARCHAR(64)                             NOT NULL,
    ip        VARCHAR(64)                             NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_hit_id PRIMARY KEY (id),
    CONSTRAINT fk_hit_app_id FOREIGN KEY (app_id) REFERENCES apps (id)
);

