DROP TABLE IF EXISTS endpoint_hit CASCADE;

CREATE TABLE endpoint_hit
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(64)                             NOT NULL,
    uri       VARCHAR(2083)                            NOT NULL,
    ip        VARCHAR(49)                             NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL
);
